version: "3.9"
services:
  db:
    image: postgres:14.2
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test-db
    ports:
      - "5432:5432"